# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_article_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='board',
            new_name='bord',
        ),
    ]
