# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20170704_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='bord',
            new_name='board',
        ),
    ]
