# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170704_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('acount_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acount', models.CharField(max_length=50)),
            ],
        ),
    ]
