# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_remove_article_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acount_id',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
