# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20170929_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
