# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20170929_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='context',
        ),
    ]
