# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20170929_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.TextField(default=None),
        ),
    ]
