# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20170929_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pusher', models.CharField(default=None, max_length=30)),
                ('content', models.TextField(default=None)),
                ('time', models.CharField(default=None, max_length=50)),
                ('tag', models.SmallIntegerField(default=None)),
                ('author', models.CharField(default=None, max_length=30)),
                ('title', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
