# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blue_n',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='blue_p',
            field=models.IntegerField(default=None),
        ),
    ]
