# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_article_pusher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pusher',
        ),
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.article'),
        ),
    ]
