# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_auto_20171016_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='firstapp.article'),
        ),
    ]
