# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_auto_20171016_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_2013',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_2014',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_2015',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_2016',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_2017',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='_2018',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
