# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_auto_20171016_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=None, max_length=30)),
                ('tendency', models.IntegerField(default=-1)),
                ('acount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.User')),
            ],
        ),
    ]
