# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_2013',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_2014',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_2015',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_2016',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_2017',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_2018',
        ),
        migrations.AddField(
            model_name='push',
            name='mood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=-1),
        ),
    ]
