# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_auto_20171018_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(default='', max_length=30),
        ),
    ]
