# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_remove_push_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.article'),
        ),
    ]
