# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_auto_20171025_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='push',
            name='out_key',
        ),
        migrations.AddField(
            model_name='push',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firstapp.article'),
        ),
    ]
