# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_remove_push_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='tag',
            field=models.SmallIntegerField(default=0),
        ),
    ]
