# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_auto_20171025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='year',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='push',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='push',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='push',
            name='pusher',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='push',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
