# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_auto_20171025_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.article'),
        ),
    ]
