# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_auto_20171025_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='title_value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
